export enum PermissionsGroups {
  ROLES = 'ROLES',
  ADMINS = 'ADMINS',
  CUSTOMERS = 'CUSTOMERS',
  VENDORS = 'VENDORS',
  PRODUCTS = 'PRODUCTS',
  ORDERS = 'ORDERS',
  REASONS = 'REASONS',
  DOCUMENTS = 'DOCUMENTS',
  LOCATIONS = 'LOCATIONS',
  COMPLAINS = 'COMPLAINS',
  ON_BOARDING_SCREENS = 'ON_BOARDING_SCREENS',
  SETTINGS = 'SETTINGS',
}
